#!/usr/bin/env python3
"""Build map/routes.js: one FeatureCollection of all routes for the map page."""
import colorsys
import csv
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / "data"
OUT = Path(__file__).resolve().parent.parent / "map"
OUT.mkdir(exist_ok=True)


def color_for(i, n):
    """Golden-angle hue walk, two lightness tiers, tuned for a light basemap."""
    h = (i * 137.508) % 360 / 360
    light = 0.38 if i % 2 else 0.50
    r, g, b = colorsys.hls_to_rgb(h, light, 0.72)
    return "#{:02x}{:02x}{:02x}".format(int(r * 255), int(g * 255), int(b * 255))


def infer_places(display_name):
    """No-geometry routes: match route-name tokens against OSM place names
    so 'RUTA ZINACATEPEC' searches as 'San Sebastián Zinacatepec'."""
    osm = Path(__file__).resolve().parent.parent / "data" / "raw" / "osm" / "places.json"
    if not osm.exists():
        return ""
    hits = []
    dn = display_name.lower()
    for p in json.loads(osm.read_text()):
        for tok in p["name"].lower().split():
            if len(tok) > 5 and tok in dn:
                hits.append(p["name"])
                break
    return ", ".join(dict.fromkeys(hits))


def main():
    rows = list(csv.DictReader((BASE / "master_route_index.csv").open()))
    places_path = BASE / "route_places.json"
    route_places = json.loads(places_path.read_text()) if places_path.exists() else {}
    feats = []
    idx = 0
    for r in rows:
        files = [f.strip() for f in r["geometry_files"].split(";") if f.strip()]
        lines = []
        for fp in files[:1]:
            gj = json.loads((BASE / fp).read_text())
            for f in gj["features"]:
                g = f.get("geometry") or {}
                if g.get("type") == "LineString":
                    lines.append([[round(x, 6), round(y, 6)] for x, y, *_ in g["coordinates"]])
                elif g.get("type") == "MultiLineString":
                    lines += [[[round(x, 6), round(y, 6)] for x, y, *_ in part] for part in g["coordinates"]]
        if not lines:
            continue  # geometry-less rows stay in the CSV but off the map (see notes column)
        feats.append({
            "type": "Feature",
            "properties": {
                "id": r["route_key"],
                "name": r["display_name"],
                "alias": r.get("known_as", ""),
                "colonias": r.get("colonias", ""),
                "places": ", ".join(p["name"] for p in route_places.get(r["route_key"], [])) or infer_places(r["display_name"]),
                "kind": r["kind"],
                "sources": r["sources"],
                "color": color_for(idx, len(rows)) if lines else "#8a8a94",
                "geom_source": files[0].split("/")[1] if files else "",
                "has_geom": bool(lines),
                "review": "human review" in r["notes"],
            },
            "geometry": {"type": "MultiLineString", "coordinates": lines},
        })
        idx += 1

    fc = {"type": "FeatureCollection", "features": feats}
    js = "// generated by scripts/06_build_map.py — do not edit\nconst ROUTES = " + json.dumps(fc, ensure_ascii=False, separators=(",", ":")) + ";\n"
    (OUT / "routes.js").write_text(js, encoding="utf-8")
    kb = len(js) // 1024
    print(f"map/routes.js: {len(feats)} routes, {kb} KB")


if __name__ == "__main__":
    main()
