#!/usr/bin/env python3
"""Build map/sponsors.js: seed sponsors + per-route nearby locations (PRD-revenue.md).

Seed sponsors show on every route view; their location pins show only for
locations within NEAR_M of the selected route's geometry.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NEAR_M = 300
MLON = 111320 * math.cos(math.radians(18.462)); MLAT = 110570

SPONSORS = {
    "oxxo": {
        "name": "OXXO",
        "logo": "patrocinadores/oxxo.png",
        "logo2x": "patrocinadores/oxxo@2x.png",
        "seed": True,  # placeholder per PRD-revenue §3 — replaced by first paying sponsor
        "locations_file": ROOT / "data" / "sponsors" / "oxxo_locations.json",
    },
}


def main():
    routes = json.loads((ROOT / "map" / "routes.js").read_text().split("const ROUTES = ", 1)[1].rstrip().rstrip(";"))

    flat = {}
    for f in routes["features"]:
        flat[f["properties"]["id"]] = [(c[0] * MLON, c[1] * MLAT)
                                       for part in f["geometry"]["coordinates"] for c in part]

    out = {"sponsors": {}, "by_route": {}}
    for sid, s in SPONSORS.items():
        locs = json.loads(s["locations_file"].read_text())["locations"]
        out["sponsors"][sid] = {"name": s["name"], "logo": s["logo"], "logo2x": s["logo2x"], "seed": s["seed"]}
        for rid, pts in flat.items():
            near = []
            for loc in locs:
                lx, ly = loc["lon"] * MLON, loc["lat"] * MLAT
                d = min(math.hypot(px - lx, py - ly) for px, py in pts)  # meters
                if d <= NEAR_M:
                    near.append([round(loc["lon"], 6), round(loc["lat"], 6), loc.get("addr") or loc.get("name") or s["name"]])
            if near:
                out["by_route"].setdefault(rid, {})[sid] = near

    js = "// generated by scripts/12_build_sponsors.py — do not edit\nconst SPONSORS = " + \
         json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n"
    (ROOT / "map" / "sponsors.js").write_text(js, encoding="utf-8")
    n_routes = len(out["by_route"])
    n_pins = sum(len(v) for r in out["by_route"].values() for v in r.values())
    print(f"map/sponsors.js: {len(out['sponsors'])} sponsor(s), pins on {n_routes} routes ({n_pins} route-pin pairs)")


if __name__ == "__main__":
    main()
