#!/usr/bin/env python3
"""Build the public-service POI layer (map/pois.js) from OpenStreetMap data.

POIs are PUBLIC SERVICES only — schools, health, government offices (SAT/SHCP,
ayuntamientos, correos, policía). Commercial placement is the sponsor pipeline
(12_build_sponsors.py); never mix the two.

Input:  poi/pois_osm.json — raw Overpass result, refreshed with:
        nwr["amenity"~"^(school|kindergarten|college|university)$"](around:30000,18.462,-97.396);
        nwr["amenity"~"^(townhall|courthouse|police|post_office|hospital|clinic|library)$"](...);
        nwr["office"="government"](...); nwr["healthcare"~"^(hospital|clinic|centre)$"](...)
        (SEP's CCT school registry is the follow-up source for full school coverage —
        OSM only has a fraction of the region's schools.)
Output: map/pois.js — const POIS = {pois: [{n, c:[lon,lat], k}], by_route: {route_id: [idx,...]}}
        k: edu | salud | gob. A POI attaches to every route that passes within WALK_M.
"""
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WALK_M = 180  # a POI belongs to a route if the line passes within this many meters
              # (400 read as "too far from the line" on the map — keep it tight)

CAT = {
    "school": "edu", "kindergarten": "edu", "college": "edu", "university": "edu", "library": "edu",
    "hospital": "salud", "clinic": "salud", "centre": "salud",
    "townhall": "gob", "courthouse": "gob", "police": "gob", "post_office": "gob", "government": "gob",
}
FALLBACK_NAME = {"school": "Escuela", "kindergarten": "Preescolar", "college": "Escuela superior",
                 "university": "Universidad", "library": "Biblioteca", "hospital": "Hospital",
                 "clinic": "Clínica", "centre": "Centro de salud", "townhall": "Palacio municipal",
                 "courthouse": "Juzgado", "police": "Policía", "post_office": "Correos",
                 "government": "Oficina de gobierno"}


def load_routes():
    txt = (ROOT / "map" / "routes.js").read_text(encoding="utf-8")
    return json.loads(txt[txt.index("{"):txt.rstrip().rstrip(";").rindex("}") + 1])


def meter_space(lat0):
    mlon = 111320 * math.cos(math.radians(lat0))
    return lambda lon, lat: (lon * mlon, lat * 110570)


def dist_point_polyline(px, py, pts):
    best = float("inf")
    for (ax, ay), (bx, by) in zip(pts, pts[1:]):
        abx, aby = bx - ax, by - ay
        len2 = abx * abx + aby * aby
        t = 0.0 if len2 == 0 else max(0.0, min(1.0, ((px - ax) * abx + (py - ay) * aby) / len2))
        dx, dy = px - (ax + t * abx), py - (ay + t * aby)
        d = math.hypot(dx, dy)
        if d < best:
            best = d
    return best


def main():
    raw = json.loads((ROOT / "poi" / "pois_osm.json").read_text(encoding="utf-8"))
    routes = load_routes()
    to_m = meter_space(18.462)

    # flatten route geometry to meter-space polylines (one list of parts per route)
    flat = []
    for f in routes["features"]:
        parts = [[to_m(lon, lat) for lon, lat in part] for part in f["geometry"]["coordinates"]]
        flat.append((f["properties"]["id"], parts))

    pois, seen = [], set()
    for el in raw["elements"]:
        tags = el.get("tags", {})
        kind = tags.get("amenity") or tags.get("office") or tags.get("healthcare")
        cat = CAT.get(kind)
        if not cat:
            continue
        lon = el.get("lon") or (el.get("center") or {}).get("lon")
        lat = el.get("lat") or (el.get("center") or {}).get("lat")
        if lon is None:
            continue
        name = (tags.get("name") or FALLBACK_NAME.get(kind, "")).strip()
        if not name:
            continue
        key = (round(lon, 5), round(lat, 5), name.lower())
        if key in seen:  # ways+nodes for the same campus
            continue
        seen.add(key)
        pois.append({"n": name[:80], "c": [round(lon, 6), round(lat, 6)], "k": cat})

    by_route = {}
    for rid, parts in flat:
        near = []
        for i, p in enumerate(pois):
            px, py = to_m(*p["c"])
            if min(dist_point_polyline(px, py, pp) for pp in parts if len(pp) > 1) <= WALK_M:
                near.append(i)
        if near:
            by_route[rid] = near

    out = {"pois": pois, "by_route": by_route}
    (ROOT / "map" / "pois.js").write_text(
        "// generated by scripts/15_build_pois.py — do not edit (public services only;\n"
        "// commercial placement lives in sponsors.js)\n"
        "const POIS = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    n_linked = len({i for v in by_route.values() for i in v})
    print(f"pois: {len(pois)} total, {n_linked} within {WALK_M} m of a route, "
          f"{len(by_route)} routes with POIs -> map/pois.js")


if __name__ == "__main__":
    main()
